src_dir: "./../../example_data"                 # Local folder, relative path from execution point
target_path: "<destination-folder>"     # Destination folder
overwrite: false                                # Whether to overwrite existing data
show_progress: false