# Root data folder:
root_data_dir:         "./example_data"

images:                "images"
masks:                 "masks"
folds:                 "folds"
scaled:                "scaled"
patches:               "patches"
tiger_annotations:     "tiger_coco.json"
tnbc_binary_masks:     "binary_masks"

raw_train:              "raw_train"
raw_test:               "raw_test"
processed_train:        "processed_train"
processed_test:         "processed_test"

source_dirs:
  raw_eq:              "eq"
  normalized:          "normalized"
  normalized_eq:       "normalized_eq"
  hematoxylin:         "hematoxylin"
  hematoxylin_eq:      "hematoxylin_eq"

pseudo_mask_dirs:
  all:
    - "hematoxylin_adaptive"
    - "hematoxylin_otsu"
    - "hematoxylin_blur_adaptive"
    - "hematoxylin_blur_otsu"
    - "hematoxylin_eq_adaptive"
    - "hematoxylin_eq_otsu"
    - "hematoxylin_eq_blur_adaptive"
    - "hematoxylin_eq_blur_otsu"
    - "normalized_adaptive"
    - "normalized_otsu"
    - "normalized_blur_adaptive"
    - "normalized_blur_otsu"
    - "normalized_eq_adaptive"
    - "normalized_eq_otsu"
    - "normalized_eq_blur_adaptive"
    - "normalized_eq_blur_otsu"
    - "raw_adaptive"
    - "raw_otsu"
    - "raw_blur_adaptive"
    - "raw_blur_otsu"
    - "raw_eq_adaptive"
    - "raw_eq_otsu"
    - "raw_eq_blur_adaptive"
    - "raw_eq_blur_otsu"
  best_25:
    - "normalized_eq_adaptive"
    - "normalized_eq_otsu"
    - "hematoxylin_eq_blur_otsu"
    - "normalized_eq_blur_adaptive"
    - "raw_otsu"
    - "normalized_blur_otsu"
  best_50:
    - "raw_eq_adaptive"
    - "hematoxylin_blur_otsu"
    - "normalized_eq_blur_otsu"
    - "normalized_adaptive"
    - "hematoxylin_eq_blur_adaptive"
    - "hematoxylin_blur_adaptive"
    # + best_25 list
  best_75:
    - "normalized_eq_adaptive"
    - "raw_eq_blur_adaptive"
    - "raw_adaptive"
    - "raw_blur_otsu"
    - "raw_eq_otsu"
    - "normalized_otsu"
    # + best_50 list
  fused:
    - "fused_all"
    - "fused_best_25"
    - "fused_best_50"
    - "fused_best_75"
    - "fused_leave_0_out"
    - "fused_leave_1_out"
    - "fused_leave_2_out"
    - "fused_leave_3_out"
